const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('midnightAPI', {
  getSystemInfo: () => ipcRenderer.invoke('get-system-info'),
  powerHigh: () => ipcRenderer.invoke('opt-power-high'),
  powerBalanced: () => ipcRenderer.invoke('opt-power-balanced'),
  gameMode: (enable) => ipcRenderer.invoke('opt-game-mode', enable),
  gameBar: (disable) => ipcRenderer.invoke('opt-game-bar', disable),
  cleanTemp: () => ipcRenderer.invoke('opt-clean-temp'),
  network: () => ipcRenderer.invoke('opt-network'),
  visualEffects: (perf) => ipcRenderer.invoke('opt-visual-effects', perf),
  killBackground: () => ipcRenderer.invoke('opt-kill-background'),
  gpuPriority: () => ipcRenderer.invoke('opt-gpu-priority'),
  privacyOn: () => ipcRenderer.invoke('opt-privacy-on'),
  privacyOff: () => ipcRenderer.invoke('opt-privacy-off'),
  gamingExtra: (enable) => ipcRenderer.invoke('opt-gaming-extra', enable),
  systemExtra: (enable) => ipcRenderer.invoke('opt-system-extra', enable),
  debloat: () => ipcRenderer.invoke('opt-debloat'),
  privacyExtra: (enable) => ipcRenderer.invoke('opt-privacy-extra', enable),
  servicesGaming: (enable) => ipcRenderer.invoke('opt-services', enable),
  schedTasks: (enable) => ipcRenderer.invoke('opt-schedtasks', enable),
  updatesManual: (enable) => ipcRenderer.invoke('opt-updates', enable),
  soundTweaks: (enable) => ipcRenderer.invoke('opt-sound', enable),
  winNotify: (enable) => ipcRenderer.invoke('opt-winnotify', enable),
  customize: (enable) => ipcRenderer.invoke('opt-customize', enable),
  powerExtra: (enable) => ipcRenderer.invoke('opt-power-extra', enable),
  perfExtra: (enable) => ipcRenderer.invoke('opt-perf-extra', enable),
  analyzePc: () => ipcRenderer.invoke('analyze-pc'),
  competitiveOn: () => ipcRenderer.invoke('competitive-on'),
  competitiveOff: () => ipcRenderer.invoke('competitive-off'),
  launchGame: (p) => ipcRenderer.invoke('launch-game-boosted', p),
  bugsList: () => ipcRenderer.invoke('bugs-list'),
  bugsAdd: (t) => ipcRenderer.invoke('bugs-add', t),
  autostartGet: () => ipcRenderer.invoke('autostart-get'),
  autostartSet: (e) => ipcRenderer.invoke('autostart-set', e),
});
