# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('index.html', '.'),
        ('styles.css', '.'),
        ('interface.css', '.'),
        ('interface.js', '.'),
        ('renderer.js', '.'),
        ('assets', 'assets'),
        ('pros.py', '.'),
        ('game_tweaks.py', '.'),
        ('overlay.py', '.'),
        ('voicefx.py', '.'),
        ('accounts.py', '.'),
        ('oauth_login.py', '.'),
        ('servers.py', '.'),
        ('online.py', '.'),
        ('voicemod_importer.py', '.'),
        ('voicemod_sounds.json', '.'),
    ],
    hiddenimports=[
        'pros',
        'game_tweaks',
        'overlay',
        'voicefx',
        'accounts',
        'oauth_login',
        'servers',
        'online',
        'voicemod_importer',
        'soundfile',
        '_soundfile',
        'cffi',
        '_cffi_backend',
        'tkinter',
        'webview',
        'webview.platforms.winforms',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PulseOptimizer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets/icon.ico'],
)
